### ISSUE TITLE
enhancements to grids (new ones)

### ISSUE THREAD

**Issue by jasper-e** [muparkkra/mup#1144]
There are two shorthand notations for which I would highly appreciate support from Mup -- the problem is with grids only

1. sometimes instead of chords like
`rom chord above 1: 1.0 "C"; 2.0 "C/B"; 3.0 "C/A"; 4.0 "C/G";`
I have shortened variation
`rom chord above 1: 1.0 "C"; 2.0 "/B"; 3.0 "/A"; 4.0 "/G";`
 I would like to be able to add the grids somehow manually when grids are displayed at the end ( I mean C/B, C/A, C/G)

2. minor one: chord name in parentheses: typical when the song ends with a repetition, and there is a chord only to play when repetition is still to be done. Endings are theoretically possible but are an overkill and makes the music sheet more hard to read...
I would prefer Mup to find the grid definition without parameters -- for example `"C^7"` instead of `"(C^7)"` -- as a fallback. This could make life easier, manual workarounds are typically possible here.

**Comment by muparkkra** [comment]
Both of these could be handled by allowing an optional label, to be printed instead of the actual chord name. So something like
  rom chord above 1: 2.0 "C/B" ("/B");  4.0 "C^7" ("(C^7)");
Internally, Mup would use the real chord name for printing the grid, but the alternate name for the label.  Doing in a general way like that would provide the flexibility for other possible uses.

**Comment by muparkkra** [comment]
Mup 7.1 adds the ability to supply an alternate label to be printed
